steps:
  # Get GKE credentials
  - name: gcr.io/cloud-builders/gcloud
    id: "Fetch GKE Credentials"
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "cloud-a3-gke-cluster"
      - "--zone"
      - "us-central1-b"
      - "--project"
      - "cloud-a3-453520"

  # Apply PVC configuration
  - name: gcr.io/cloud-builders/kubectl
    id: "Deploy PersistentVolumeClaim"
    args:
      - "apply"
      - "-f"
      - "./pvc/pvc.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-east1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=cloud-a3-gke-cluster"
