steps:
  # Get GKE credentials
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "container"
      - "clusters"
      - "get-credentials"
      - "cloud-a3-gke-cluster"
      - "--zone"
      - "us-central1-b"
    id: "Set up kubectl"

  # Deploy the latest image to GKE
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "kubectl"
      - "apply"
      - "-f"
      - "pvc/pvc.yaml"
    id: "Deploy pvc to GKE"
