gcp_credentials="cloud-a3-453520-589f9f4cd09c.json"
gcp_project_id="cloud-a3-453520"
gke_cluster_name="cloud-a3-gke-cluster"
gcp_region= "us-central1"
gke_regional=false
gke_zones_list=["us-central1-b"]
gke_vpc = "default"
gke_subnet = "default"
gke_node_pools_name = "cloud-a3-gke-node-pool"
gke_service_account_name="cloud-a3-service-account@cloud-a3-453520.iam.gserviceaccount.com"