steps:
  # Build Docker image for container2
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/cloud-a3-453520/cloud-a3-container-second/cloud-a3-container-second:latest",
        "./container2",
      ]

  # Push Docker image for container2
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/cloud-a3-453520/cloud-a3-container-second/cloud-a3-container-second:latest",
      ]

  # Set up kubectl and authenticate with GKE
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "container"
      - "clusters"
      - "get-credentials"
      - "cloud-a3-gke-cluster"
      - "--zone"
      - "us-central1-b"
    id: "Set up kubectl"

  # Deploy the latest image to GKE
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "kubectl"
      - "apply"
      - "-f"
      - "container2/k8s/container2-deployment.yaml"
    id: "Deploy container2 to GKE"

images:
  - "us-east1-docker.pkg.dev/cloud-a3-453520/cloud-a3-container-second/cloud-a3-container-second:latest"

options:
  logging: CLOUD_LOGGING_ONLY